### ISSUE TITLE
Set up Circle CI

### ISSUE THREAD

**Issue by letrunghieu** [reecms/reecms#31]

**Comment by tabenguyen** [comment]
Assign to tabe

**Comment by tabenguyen** [comment]
## Setup Circle CI done

Currently, CircleCI auto run
- npm install
- composer install
- phpunit
  In case building fail, message will be sent to slack#github

**Comment by letrunghieu** [comment]
Now, failed builds will not be deployed to Heroku any longer.

**Comment by tabenguyen** [comment]
File circle.yaml will be updated continuously belongs to new feature. 
I think all change in this file should refer to this issue for easy trace.

**Comment by letrunghieu** [comment]
:+1:
